/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import controller.Filho;
import controller.Funcionario;
import java.awt.event.KeyEvent;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import models.FunModel;

/**
 *
 * @author Cassiano Silva
 */
public class FormFunLista extends javax.swing.JDialog {

    SimpleDateFormat df = new SimpleDateFormat("dd/MM/yyyy");
    List<Funcionario> f;
    DefaultTableModel tabelaFilhos;

    /**
     * Creates new form FormFunLista
     */
    public FormFunLista() {
        initComponents();
        tabelaFilhos = (DefaultTableModel) tbFilhos.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbListaFun = new javax.swing.JTable();
        btCad = new javax.swing.JButton();
        btExcluir = new javax.swing.JButton();
        btAlterar = new javax.swing.JButton();
        btSair = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbFilhos = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("ListadeFuncionarios");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        tbListaFun.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tbListaFun.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbListaFunMouseClicked(evt);
            }
        });
        tbListaFun.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tbListaFunKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tbListaFun);

        btCad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/add/add199.png"))); // NOI18N
        btCad.setText("Cadastro");
        btCad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadActionPerformed(evt);
            }
        });

        btExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/Delete/garbage12.png"))); // NOI18N
        btExcluir.setText("Excluir");
        btExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirActionPerformed(evt);
            }
        });

        btAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/Editar/icons8-limpar-formatação-30.png"))); // NOI18N
        btAlterar.setText("Alterar");
        btAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAlterarActionPerformed(evt);
            }
        });

        btSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/sair/icons8-sair-30.png"))); // NOI18N
        btSair.setText("Sair");
        btSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairActionPerformed(evt);
            }
        });

        tbFilhos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nome"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tbFilhos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 780, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btCad)
                        .addGap(26, 26, 26)
                        .addComponent(btAlterar)
                        .addGap(18, 18, 18)
                        .addComponent(btExcluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btSair)
                        .addGap(10, 10, 10)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btCad)
                    .addComponent(btAlterar)
                    .addComponent(btExcluir)
                    .addComponent(btSair))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairActionPerformed
        dispose();
    }//GEN-LAST:event_btSairActionPerformed
    private void listarFilhos() {
        limparFilhos();
        FunModel fm = new FunModel();
        Funcionario f = fm.listaUnicoFun((Long) tbListaFun.getValueAt(tbListaFun.getSelectedRow(), 0));
        for (Filho filho : f.getFilhos()) {
            tabelaFilhos.addRow(new Object[]{filho.getId(), filho.getNome()});
        }
        //tbFilhos.setModel(new DefaultTableModel(
        // new Object[][]{}, new String[]{"Coódigo", "Nome"}));
    }

    private void limparFilhos() {
//Limpa o numero de linhas setando os numero de linhas 0
        tabelaFilhos.setNumRows(0);
        /*for (int i = 0; i < tbFilhos.getRowCount(); i++) {
            tabelaFilhos.setNumRows(0);
        }*/
    }

    private void listarFuncionarios() {
        tbListaFun.setModel(new DefaultTableModel(
                new Object[][]{}, new String[]{"Código", "Nome", "Data Cadastro", "CPF", "Telefone"}));
        DefaultTableModel tabela = (DefaultTableModel) tbListaFun.getModel();
        try {
            for (Funcionario funcionario : f) {
                tabela.addRow(new Object[]{funcionario.getId(),
                    funcionario.getNome(),
                    df.format(funcionario.getData()),
                    funcionario.getCpf(),
                    funcionario.getTelefone()});
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Erro na listagem de funcionários!");
        }
    }

    private void btCadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadActionPerformed
        FormFunCad fcad = new FormFunCad();
        fcad.setModal(true);
        fcad.setVisible(true);
    }//GEN-LAST:event_btCadActionPerformed

    private void btExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirActionPerformed
        // FunModel fmo = new FunModel();
        if (tbListaFun.getSelectedRow() < 0) {
            JOptionPane.showInputDialog(rootPane, "Selecione uma linha da tabela");
        } else {
            try {
                if (JOptionPane.showConfirmDialog(rootPane, "Confirma exlusão do Registro?") == 0) {
                    new FunModel().remover((Long) tbListaFun.getValueAt(tbListaFun.getSelectedRow(), 0));
                    JOptionPane.showMessageDialog(rootPane, "Registro removido");
                }

            } catch (Exception e) {
                JOptionPane.showMessageDialog(rootPane, "Erro ao excluir registro");
            }
        }
    }//GEN-LAST:event_btExcluirActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        FunModel fModel = new FunModel();
        f = fModel.listarOrdemNomes();
        listarFuncionarios();
    }//GEN-LAST:event_formWindowOpened

    private void btAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAlterarActionPerformed
        try {
            FormFunCad fcad = new FormFunCad();
            fcad.situacao = "alterar";
            fcad.f.setId((Long) tbListaFun.getValueAt(tbListaFun.getSelectedRow(), 0));
            fcad.f.setNome((String) tbListaFun.getValueAt(tbListaFun.getSelectedRow(), 1));
            fcad.f.setData(df.parse((String) tbListaFun.getValueAt(tbListaFun.getSelectedRow(), 2)));
            fcad.f.setCpf((String) tbListaFun.getValueAt(tbListaFun.getSelectedRow(), 3));
            fcad.f.setTelefone((String) tbListaFun.getValueAt(tbListaFun.getSelectedRow(), 4));
            for (int i = 0; i < tbFilhos.getRowCount(); i++) {
                fcad.filhos.add(new Filho(
                        (Long)tbFilhos.getValueAt(i, 0), 
                        (String)tbFilhos.getValueAt(i, 1), 
                        null));
            }
            fcad.setTitle("Alteração de Cadastro");
            fcad.setModal(true);
            fcad.setVisible(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Selecione um funcionário");
        }

    }//GEN-LAST:event_btAlterarActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        formWindowOpened(evt);
    }//GEN-LAST:event_formWindowActivated

    private void tbListaFunMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbListaFunMouseClicked
        listarFilhos();
    }//GEN-LAST:event_tbListaFunMouseClicked

    private void tbListaFunKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbListaFunKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_UP || evt.getKeyCode() == KeyEvent.VK_DOWN) {
            listarFilhos();
        }
    }//GEN-LAST:event_tbListaFunKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormFunLista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormFunLista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormFunLista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormFunLista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormFunLista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAlterar;
    private javax.swing.JButton btCad;
    private javax.swing.JButton btExcluir;
    private javax.swing.JButton btSair;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tbFilhos;
    private javax.swing.JTable tbListaFun;
    // End of variables declaration//GEN-END:variables
}
