package views;

import controller.Produto;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import models.ProdModel;

public class FormProList extends javax.swing.JDialog {
   
    //Produto pd = new Produto();
    List<Produto> p;

    public FormProList() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbListPro = new javax.swing.JTable();
        btCadPro = new javax.swing.JButton();
        btAlterarProd = new javax.swing.JButton();
        btExcluirProd = new javax.swing.JButton();
        btSair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        tbListPro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tbListPro);

        btCadPro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/youtube/add-new-document_icon-icons.com_54068.png"))); // NOI18N
        btCadPro.setText("Cadastro");
        btCadPro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadProActionPerformed(evt);
            }
        });

        btAlterarProd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/Delete/icons8-lápis-30.png"))); // NOI18N
        btAlterarProd.setText("Alterar");
        btAlterarProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAlterarProdActionPerformed(evt);
            }
        });

        btExcluirProd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/Delete/garbage12.png"))); // NOI18N
        btExcluirProd.setText("Excluir");
        btExcluirProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirProdActionPerformed(evt);
            }
        });

        btSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/sair/icons8-sair-30.png"))); // NOI18N
        btSair.setText("Sair");
        btSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btCadPro)
                        .addGap(33, 33, 33)
                        .addComponent(btAlterarProd)
                        .addGap(34, 34, 34)
                        .addComponent(btExcluirProd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 272, Short.MAX_VALUE)
                        .addComponent(btSair)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btCadPro)
                    .addComponent(btAlterarProd)
                    .addComponent(btExcluirProd)
                    .addComponent(btSair))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairActionPerformed
        dispose();
    }//GEN-LAST:event_btSairActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        ProdModel pModel = new ProdModel();
        p = pModel.listarOrdemNome();
        listarProdutos();
    }//GEN-LAST:event_formWindowOpened

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        formWindowOpened(evt);
    }//GEN-LAST:event_formWindowActivated

    private void btCadProActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadProActionPerformed
        FormProdCad pcad = new FormProdCad();
        pcad.setModal(true);
        pcad.setVisible(true);
    }//GEN-LAST:event_btCadProActionPerformed

    private void btExcluirProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirProdActionPerformed
        if (tbListPro.getSelectedRow() < 0) {
            JOptionPane.showInputDialog(rootPane, "Selecione uma linha da tabela");
        } else {
            try {
                if (JOptionPane.showConfirmDialog(rootPane, "Confirma exlusão do Registro?") == 0) {
                    new ProdModel().remover((Long) tbListPro.getValueAt(tbListPro.getSelectedRow(), 0));
                    JOptionPane.showMessageDialog(rootPane, "Registro removido");
                }

            } catch (Exception e) {
                JOptionPane.showMessageDialog(rootPane, "Erro ao excluir registro");
            }
        }
    }//GEN-LAST:event_btExcluirProdActionPerformed

    private void btAlterarProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAlterarProdActionPerformed
        try {
            FormProdCad pcad = new FormProdCad();
            pcad.situacao = "alterar";

            pcad.p.setId((Long) tbListPro.getValueAt(tbListPro.getSelectedRow(), 0));
            pcad.p.setNome((String) tbListPro.getValueAt(tbListPro.getSelectedRow(), 1));
            pcad.p.setQtde(Integer.parseInt((String) tbListPro.getValueAt(tbListPro.getSelectedRow(), 2)));
            pcad.p.setUn((String) tbListPro.getValueAt(tbListPro.getSelectedRow(), 3));
            pcad.p.setValor(Double.parseDouble((String) tbListPro.getValueAt(tbListPro.getSelectedRow(), 4)));

            pcad.setTitle("Alteração de Produto");
            pcad.setModal(true);
            pcad.setVisible(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e.getMessage());
        }
    }//GEN-LAST:event_btAlterarProdActionPerformed
    private void listarProdutos() {
        tbListPro.setModel(new DefaultTableModel(
                new Object[][]{}, new String[]{"Código", "Nome", "Quantidade", "Unidade", "Valor"}));
        DefaultTableModel tabela = (DefaultTableModel) tbListPro.getModel();
        try {
            for (Produto produto : p) {
                tabela.addRow(new Object[]{produto.getId(),
                    produto.getNome(),
                    produto.getQtde(),
                    produto.getUn(),
                    produto.getValor()});
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Erro na listagem de produtos!");
        }
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormProList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormProList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormProList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormProList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormProList().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAlterarProd;
    private javax.swing.JButton btCadPro;
    private javax.swing.JButton btExcluirProd;
    private javax.swing.JButton btSair;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbListPro;
    // End of variables declaration//GEN-END:variables
}
