/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

/**
 *
 * @author Cassiano Silva
 */
public class FormPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FormPrincipal
     */
    public FormPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnAbrir = new javax.swing.JMenu();
        mnAbrirFuncionario = new javax.swing.JMenu();
        mnAbrirFunCad = new javax.swing.JMenuItem();
        mnAbrirFunLista = new javax.swing.JMenuItem();
        mnAbrirCadProd = new javax.swing.JMenu();
        mnCadPro = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        mnSistema = new javax.swing.JMenu();

        jMenuItem2.setText("jMenuItem2");

        jMenuItem3.setText("jMenuItem3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Aplicação Empresarial");

        mnAbrir.setText("Abrir");

        mnAbrirFuncionario.setText("Funcionário");

        mnAbrirFunCad.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK));
        mnAbrirFunCad.setText("Cadastro");
        mnAbrirFunCad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnAbrirFunCadActionPerformed(evt);
            }
        });
        mnAbrirFuncionario.add(mnAbrirFunCad);

        mnAbrirFunLista.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.ALT_MASK));
        mnAbrirFunLista.setText("Lista");
        mnAbrirFunLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnAbrirFunListaActionPerformed(evt);
            }
        });
        mnAbrirFuncionario.add(mnAbrirFunLista);

        mnAbrir.add(mnAbrirFuncionario);

        mnAbrirCadProd.setText("Produto");
        mnAbrirCadProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnAbrirCadProdActionPerformed(evt);
            }
        });

        mnCadPro.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.ALT_MASK));
        mnCadPro.setText("Cadastro");
        mnCadPro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnCadProActionPerformed(evt);
            }
        });
        mnAbrirCadProd.add(mnCadPro);

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem1.setText("Lista de Produtos");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        mnAbrirCadProd.add(jMenuItem1);

        mnAbrir.add(mnAbrirCadProd);

        jMenuBar1.add(mnAbrir);

        mnSistema.setText("Sistema");
        jMenuBar1.add(mnSistema);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 798, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 546, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mnAbrirFunCadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnAbrirFunCadActionPerformed
        FormFunCad fcad = new FormFunCad();
        fcad.setModal(true);
        fcad.setVisible(true);
    }//GEN-LAST:event_mnAbrirFunCadActionPerformed

    private void mnAbrirFunListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnAbrirFunListaActionPerformed
       FormFunLista fLista = new FormFunLista();
        fLista.setModal(true);
        fLista.setVisible(true);
    }//GEN-LAST:event_mnAbrirFunListaActionPerformed

    private void mnAbrirCadProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnAbrirCadProdActionPerformed
       
    }//GEN-LAST:event_mnAbrirCadProdActionPerformed

    private void mnCadProActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnCadProActionPerformed
        FormProdCad pcad = new FormProdCad();
       pcad.setModal(true);
       pcad.setVisible(true);
    }//GEN-LAST:event_mnCadProActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        FormProList flist = new FormProList();
        flist.setModal(true);
        flist.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenu mnAbrir;
    private javax.swing.JMenu mnAbrirCadProd;
    private javax.swing.JMenuItem mnAbrirFunCad;
    private javax.swing.JMenuItem mnAbrirFunLista;
    private javax.swing.JMenu mnAbrirFuncionario;
    private javax.swing.JMenuItem mnCadPro;
    private javax.swing.JMenu mnSistema;
    // End of variables declaration//GEN-END:variables
}
